server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo2?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: 123
    hikari:
      idle-timeout: 6000
      maximum-pool-size: 30
      minimum-idle: 10
  application:
    name: service-provider
mybatis:
  type-aliases-package: cn.jiyun.service.springbootprovider.pojo
  mapper-locations: /mapper/*.xml
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
